In [ ]:
#PRIMER METODO DE USO DE DUCKDB

In [1]:
#IMPORTAR LIBRERIAS
import pandas as pd
import glob
import time
import duckdb

In [2]:
#DEFINIR METODO DE GUARDADO PERSISTENTE
conn = duckdb.connect("my_db.db")

In [3]:
#LEER ARCHIVOS CSV
conn.sql("""
  SELECT *
  FROM 'data/*.csv'
  LIMIT 10
""")

┌────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┬──────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬───────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────┬───────────────────────┬─────────────────┬─────────────────┬─────────┬─────────────────────┬──────────────────────────────────────┬─────────────────────┐
│                  url                   │                       name                       │ contentType │                                                                       description                                                                        │ contentRating │            genre             │                                                                                         poster                                                                                         │ formattedDuration │ releasedDate │                                                                                                                  actors                                                                                                                  │      director       │                creator                │                                           audio                                            │        subtitle         │  availableForOffline  │ numberOfSeasons │ seasonStartDate │ source  │     sourceLink      │                uniqId                │      scrapedAt      │
│                varchar                 │                     varchar                      │   varchar   │                                                                         varchar                                                                          │    varchar    │           varchar            │                                                                                        varchar                                                                                         │      varchar      │     date     │                                                                                                                 varchar                                                                                                                  │       varchar       │                varchar                │                                          varchar                                           │         varchar         │        varchar        │      int64      │      date       │ varchar │       varchar       │               varchar                │      timestamp      │
├────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────┼──────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼───────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────┼───────────────────────┼─────────────────┼─────────────────┼─────────┼─────────────────────┼──────────────────────────────────────┼─────────────────────┤
│ https://www.netflix.com/title/80189221 │ The Haunting of Hill House                       │ TVSeries    │ Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.   │ 18+           │ TV Mysteries                 │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABXWSCy7mTvNQ4R_mRaos7N9eqE0Oz4rflqohffwToR5eHOxjTH3sZFanOs6uvTJUwGMRV92DolxC9Uj3tB74I8O99MS3.jpg?r=153 │ NULL              │ 2018-10-12   │ Michiel Huisman, Carla Gugino, Timothy Hutton, Henry Thomas, Elizabeth Reaser, Oliver Jackson-Cohen, Kate Siegel, Victoria Pedretti, Lulu Wilson, Mckenna Grace, Paxton Singleton, Julian Hilliard, Violet McGraw                        │ NULL                │ Mike Flanagan                         │ NULL                                                                                       │ NULL                    │ Available to download │               1 │ 2018-10-12      │ Netflix │ https://netflix.com │ 85814dcd-729d-577f-873b-e3b7d9f21ab1 │ 2022-03-05 14:51:34 │
│ https://www.netflix.com/title/81031373 │ Don't F**k with Cats: Hunting an Internet Killer │ TVSeries    │ A twisted criminal's gruesome videos drive a group of amateur online sleuths to launch a risky manhunt that pulls them into a dark underworld.           │ 18+           │ True Crime Documentaries     │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABXdv14aKC89pGXBE-9oTdGnCYWZ46w0FSlQ5dR1JwaGhL4PVWIwoObBiLRZUSd4cp47lQMVX3zMq0BZHbDxf1dZ-9Og4.jpg?r=c09 │ NULL              │ 2019-12-18   │ NULL                                                                                                                                                                                                                                     │ Mark Lewis          │ NULL                                  │ NULL                                                                                       │ NULL                    │ Available to download │               1 │ 2019-12-18      │ Netflix │ https://netflix.com │ 134f93fc-a991-55ca-ad36-8c438b930e52 │ 2022-03-05 14:51:36 │
│ https://www.netflix.com/title/80996601 │ Love Is Blind                                    │ TVSeries    │ Nick and Vanessa Lachey host this social experiment where single men and women look for love and get engaged, all before meeting in person.              │ 16+           │ Wedding & Romance Reality TV │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABTZxF2D-iZejyj2QtyzZUbhjeP4iLovBD1KwOGp2FAVx1pGsM1lmFkZOV55adGo9HYkQdKudVVCY4oJ7kbyMUS1vWFFq.jpg?r=a2c │ NULL              │ 2020-02-13   │ Nick Lachey, Vanessa Lachey                                                                                                                                                                                                              │ NULL                │ NULL                                  │ NULL                                                                                       │ NULL                    │ Available to download │               2 │ 2020-02-13      │ Netflix │ https://netflix.com │ e5461057-25c2-59a5-8672-d4b4a102ee00 │ 2022-03-05 14:51:37 │
│ https://www.netflix.com/title/81350429 │ I Care a Lot                                     │ Movie       │ A court-appointed legal guardian defrauds her older clients and traps them under her care. But her latest mark comes with some unexpected baggage.       │ 18+           │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABTnDrXenR7tkDPdtvmVbm44VoVh2WZmrDogXjgNVd9B9cIrrj3D-pQPVO-tj2EhRTwCWztGtzM-pPdeP1FlTH9qS7gLI.jpg?r=ccb │ 1h 59m            │ 2021-02-19   │ Rosamund Pike, Peter Dinklage, Eiza González, Dianne Wiest, Chris Messina, Isiah Whitlock Jr., Macon Blair, Alicia Witt, Damian Young                                                                                                    │ J Blakeson          │ NULL                                  │ English - Audio Description, English [Original]                                            │ English, Hindi          │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ bbc71932-fc79-51aa-bf83-023c2c5db97c │ 2022-03-05 14:51:37 │
│ https://www.netflix.com/title/81149184 │ tick, tick...BOOM!                               │ Movie       │ On the brink of turning 30, a promising theater composer navigates love, friendship and the pressure to create something great before time runs out.     │ 13+           │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABVLVgTa0-KXsjVOcT5-GA5iePRDNiAvL4T5498YYjCw7rf5cmgBjzTNVMVlHKu5ha4xfSGwiuFBFBvxi7255leVJWGbK.jpg?r=cfd │ 1h 55m            │ 2021-11-19   │ Andrew Garfield, Alexandra Shipp, Vanessa Hudgens, Robin de Jesús, Joshua Henry, Bradley Whitford, Tariq Trotter, Judith Light                                                                                                           │ Lin-Manuel Miranda  │ NULL                                  │ English - Audio Description, English [Original], Hindi                                     │ English                 │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ cd630201-99b9-5ac4-bb78-7fad5c65cc95 │ 2022-03-05 14:51:38 │
│ https://www.netflix.com/title/81083626 │ Midnight Mass                                    │ TVSeries    │ The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe. │ 16+           │ TV Mysteries                 │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABc9P8ku8VMocCHKA1sMsqUQRtQAIvGHSsbV1NdCQJeeapuBP3M_B9nS0D_k4MjpoG_uYAoHy3qoo53yrSokVIYRTpSKY.jpg?r=a3e │ NULL              │ 2021-09-24   │ Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver │ Mike Flanagan       │ Mike Flanagan                         │ NULL                                                                                       │ NULL                    │ Available to download │               1 │ 2021-09-24      │ Netflix │ https://netflix.com │ d452167a-817d-5526-9070-d7fc23e8ff67 │ 2022-03-05 14:51:38 │
│ https://www.netflix.com/title/80180171 │ Kingdom                                          │ TVSeries    │ While strange rumors about their ill king grip a kingdom, the crown prince becomes their only hope against a mysterious plague overtaking the land.      │ 18+           │ Horror TV Serials            │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABU9bHervQ-EtmiZVt8zsrEhQobTSgzXGHPmHaap3Xg8K7Nk5yhuD3uLDBeBBcoqFrPlyvlzaqxPGe7KTisTxFotu0lEJ.jpg?r=e6e │ NULL              │ 2019-01-25   │ Ju Ji-hoon, Ryu Seung-ryong, Bae Doona, Kim Sang-ho, Kim Sung-kyu, Jun Suk-ho, Kim Hye-jun, Park Byung-eun, Huh Joon-ho                                                                                                                  │ NULL                │ Kim Eun-hee, Kim Seong-hun, Park Inje │ NULL                                                                                       │ NULL                    │ Available to download │               2 │ 2019-01-25      │ Netflix │ https://netflix.com │ ef1d6583-df37-5e68-b1aa-348697b6f302 │ 2022-03-05 14:51:38 │
│ https://www.netflix.com/title/81144852 │ Munich – The Edge of War                         │ Movie       │ At the tense 1938 Munich Conference, former friends who now work for opposing governments become reluctant spies racing to expose a Nazi secret.         │ 13+           │ Movies Based on Books        │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABU_ICZd89ZUGgAB3etFk8NigctyyQMRg6fS7zJBASDfJ5pwoFHV6KT1MoyU1fF0zuqr9N1_Wtnf9z6b0fJq_tf0-TVGP.jpg?r=9ed │ 2h 9m             │ 2022-01-21   │ George MacKay, Jannis Niewöhner, Jeremy Irons, Robert Bathurst, Jessica Brown Findlay, August Diehl, Sandra Hüller, Alex Jennings, Ulrich Matthes, Liv Lisa Fries                                                                        │ Christian Schwochow │ NULL                                  │ German - Audio Description, German, English - Audio Description, English [Original], Hindi │ German, German, English │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ c94d5145-fc57-584c-bb6a-0535d4ee9cfe │ 2022-03-05 14:51:39 │
│ https://www.netflix.com/title/81194110 │ Tall Girl 2                                      │ Movie       │ Landing the lead in the school musical is a dream come true for Jodi, until the pressure sends her confidence — and her relationship — into a tailspin.  │ 7+            │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABVl_RFKoWoU97Svow-lCbgOISE_N55DPGVKABn9n53BBrBh6lX6RS5BkRqRKzLYI2Q6-4UfSF5t8DKrRRvroO4ilQsgp.jpg?r=2ca │ 1h 41m            │ 2022-02-11   │ Ava Michelle, Griffin Gluck, Sabrina Carpenter, Anjelika Washington, Luke Eisner, Clara Wilsey, Rico Paris, Jan Luis Castellanos, Johanna Liauw, Steve Zahn, Angela Kinsey                                                               │ Emily Ting          │ NULL                                  │ English - Audio Description, English [Original], Hindi, Tamil, Telugu                      │ English                 │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ 62338b6f-a642-5f8e-a846-dc8fb691ddcd │ 2022-03-05 14:51:39 │
│ https://www.netflix.com/title/81028870 │ The Devil All The Time                           │ Movie       │ Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.  │ 18+           │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABfZgkFCUnggcSEVxlWY3tLvb-yKK9Jaip_EfdY9yJt9mgWskHqHqXVsexqcwCTPs_PLuyiazDHRYiE8dTBEyCo3-hclG.jpg?r=dd1 │ 2h 18m            │ 2020-09-16   │ Tom Holland, Bill Skarsgård, Riley Keough, Robert Pattinson, Mia Wasikowska, Jason Clarke, Sebastian Stan, Haley Bennett, Harry Melling, Eliza Scanlen                                                                                   │ Antonio Campos      │ NULL                                  │ English - Audio Description, English [Original]                                            │ English                 │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ 6ff23afd-bc51-5a3d-99cf-464ff3bed09b │ 2022-03-05 14:51:39 │
├────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────┴──────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴───────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────┴───────────────────────┴─────────────────┴─────────────────┴─────────┴─────────────────────┴──────────────────────────────────────┴─────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     21 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
#LEER Y MANEJAR LA INFORMACIÓN COMO DF
df=conn.sql("""
  SELECT *
  FROM 'data/*.csv'
  LIMIT 10
""").df

In [5]:
print(df)

<bound method PyCapsule.df of ┌────────────────────────────────────────┬──────────────────────────────────────────────────┬─────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┬──────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬───────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────┬───────────────────────┬─────────────────┬─────────────────┬─────────┬─────────────────────┬──────────────────────────────────────┬─────────────────────┐
│                  url                   │                       name                       │ contentType │                                                                       description                                                                        │ contentRating │            genre             │                                                                                         poster                                                                                         │ formattedDuration │ releasedDate │                                                                                                                  actors                                                                                                                  │      director       │                creator                │                                           audio                                            │        subtitle         │  availableForOffline  │ numberOfSeasons │ seasonStartDate │ source  │     sourceLink      │                uniqId                │      scrapedAt      │
│                varchar                 │                     varchar                      │   varchar   │                                                                         varchar                                                                          │    varchar    │           varchar            │                                                                                        varchar                                                                                         │      varchar      │     date     │                                                                                                                 varchar                                                                                                                  │       varchar       │                varchar                │                                          varchar                                           │         varchar         │        varchar        │      int64      │      date       │ varchar │       varchar       │               varchar                │      timestamp      │
├────────────────────────────────────────┼──────────────────────────────────────────────────┼─────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────┼──────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼───────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────┼───────────────────────┼─────────────────┼─────────────────┼─────────┼─────────────────────┼──────────────────────────────────────┼─────────────────────┤
│ https://www.netflix.com/title/80189221 │ The Haunting of Hill House                       │ TVSeries    │ Flashing between past and present, a fractured family confronts haunting memories of their old home and the terrifying events that drove them from it.   │ 18+           │ TV Mysteries                 │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABXWSCy7mTvNQ4R_mRaos7N9eqE0Oz4rflqohffwToR5eHOxjTH3sZFanOs6uvTJUwGMRV92DolxC9Uj3tB74I8O99MS3.jpg?r=153 │ NULL              │ 2018-10-12   │ Michiel Huisman, Carla Gugino, Timothy Hutton, Henry Thomas, Elizabeth Reaser, Oliver Jackson-Cohen, Kate Siegel, Victoria Pedretti, Lulu Wilson, Mckenna Grace, Paxton Singleton, Julian Hilliard, Violet McGraw                        │ NULL                │ Mike Flanagan                         │ NULL                                                                                       │ NULL                    │ Available to download │               1 │ 2018-10-12      │ Netflix │ https://netflix.com │ 85814dcd-729d-577f-873b-e3b7d9f21ab1 │ 2022-03-05 14:51:34 │
│ https://www.netflix.com/title/81031373 │ Don't F**k with Cats: Hunting an Internet Killer │ TVSeries    │ A twisted criminal's gruesome videos drive a group of amateur online sleuths to launch a risky manhunt that pulls them into a dark underworld.           │ 18+           │ True Crime Documentaries     │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABXdv14aKC89pGXBE-9oTdGnCYWZ46w0FSlQ5dR1JwaGhL4PVWIwoObBiLRZUSd4cp47lQMVX3zMq0BZHbDxf1dZ-9Og4.jpg?r=c09 │ NULL              │ 2019-12-18   │ NULL                                                                                                                                                                                                                                     │ Mark Lewis          │ NULL                                  │ NULL                                                                                       │ NULL                    │ Available to download │               1 │ 2019-12-18      │ Netflix │ https://netflix.com │ 134f93fc-a991-55ca-ad36-8c438b930e52 │ 2022-03-05 14:51:36 │
│ https://www.netflix.com/title/80996601 │ Love Is Blind                                    │ TVSeries    │ Nick and Vanessa Lachey host this social experiment where single men and women look for love and get engaged, all before meeting in person.              │ 16+           │ Wedding & Romance Reality TV │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABTZxF2D-iZejyj2QtyzZUbhjeP4iLovBD1KwOGp2FAVx1pGsM1lmFkZOV55adGo9HYkQdKudVVCY4oJ7kbyMUS1vWFFq.jpg?r=a2c │ NULL              │ 2020-02-13   │ Nick Lachey, Vanessa Lachey                                                                                                                                                                                                              │ NULL                │ NULL                                  │ NULL                                                                                       │ NULL                    │ Available to download │               2 │ 2020-02-13      │ Netflix │ https://netflix.com │ e5461057-25c2-59a5-8672-d4b4a102ee00 │ 2022-03-05 14:51:37 │
│ https://www.netflix.com/title/81350429 │ I Care a Lot                                     │ Movie       │ A court-appointed legal guardian defrauds her older clients and traps them under her care. But her latest mark comes with some unexpected baggage.       │ 18+           │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABTnDrXenR7tkDPdtvmVbm44VoVh2WZmrDogXjgNVd9B9cIrrj3D-pQPVO-tj2EhRTwCWztGtzM-pPdeP1FlTH9qS7gLI.jpg?r=ccb │ 1h 59m            │ 2021-02-19   │ Rosamund Pike, Peter Dinklage, Eiza González, Dianne Wiest, Chris Messina, Isiah Whitlock Jr., Macon Blair, Alicia Witt, Damian Young                                                                                                    │ J Blakeson          │ NULL                                  │ English - Audio Description, English [Original]                                            │ English, Hindi          │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ bbc71932-fc79-51aa-bf83-023c2c5db97c │ 2022-03-05 14:51:37 │
│ https://www.netflix.com/title/81149184 │ tick, tick...BOOM!                               │ Movie       │ On the brink of turning 30, a promising theater composer navigates love, friendship and the pressure to create something great before time runs out.     │ 13+           │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABVLVgTa0-KXsjVOcT5-GA5iePRDNiAvL4T5498YYjCw7rf5cmgBjzTNVMVlHKu5ha4xfSGwiuFBFBvxi7255leVJWGbK.jpg?r=cfd │ 1h 55m            │ 2021-11-19   │ Andrew Garfield, Alexandra Shipp, Vanessa Hudgens, Robin de Jesús, Joshua Henry, Bradley Whitford, Tariq Trotter, Judith Light                                                                                                           │ Lin-Manuel Miranda  │ NULL                                  │ English - Audio Description, English [Original], Hindi                                     │ English                 │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ cd630201-99b9-5ac4-bb78-7fad5c65cc95 │ 2022-03-05 14:51:38 │
│ https://www.netflix.com/title/81083626 │ Midnight Mass                                    │ TVSeries    │ The arrival of a charismatic young priest brings glorious miracles, ominous mysteries and renewed religious fervor to a dying town desperate to believe. │ 16+           │ TV Mysteries                 │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABc9P8ku8VMocCHKA1sMsqUQRtQAIvGHSsbV1NdCQJeeapuBP3M_B9nS0D_k4MjpoG_uYAoHy3qoo53yrSokVIYRTpSKY.jpg?r=a3e │ NULL              │ 2021-09-24   │ Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver │ Mike Flanagan       │ Mike Flanagan                         │ NULL                                                                                       │ NULL                    │ Available to download │               1 │ 2021-09-24      │ Netflix │ https://netflix.com │ d452167a-817d-5526-9070-d7fc23e8ff67 │ 2022-03-05 14:51:38 │
│ https://www.netflix.com/title/80180171 │ Kingdom                                          │ TVSeries    │ While strange rumors about their ill king grip a kingdom, the crown prince becomes their only hope against a mysterious plague overtaking the land.      │ 18+           │ Horror TV Serials            │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABU9bHervQ-EtmiZVt8zsrEhQobTSgzXGHPmHaap3Xg8K7Nk5yhuD3uLDBeBBcoqFrPlyvlzaqxPGe7KTisTxFotu0lEJ.jpg?r=e6e │ NULL              │ 2019-01-25   │ Ju Ji-hoon, Ryu Seung-ryong, Bae Doona, Kim Sang-ho, Kim Sung-kyu, Jun Suk-ho, Kim Hye-jun, Park Byung-eun, Huh Joon-ho                                                                                                                  │ NULL                │ Kim Eun-hee, Kim Seong-hun, Park Inje │ NULL                                                                                       │ NULL                    │ Available to download │               2 │ 2019-01-25      │ Netflix │ https://netflix.com │ ef1d6583-df37-5e68-b1aa-348697b6f302 │ 2022-03-05 14:51:38 │
│ https://www.netflix.com/title/81144852 │ Munich – The Edge of War                         │ Movie       │ At the tense 1938 Munich Conference, former friends who now work for opposing governments become reluctant spies racing to expose a Nazi secret.         │ 13+           │ Movies Based on Books        │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABU_ICZd89ZUGgAB3etFk8NigctyyQMRg6fS7zJBASDfJ5pwoFHV6KT1MoyU1fF0zuqr9N1_Wtnf9z6b0fJq_tf0-TVGP.jpg?r=9ed │ 2h 9m             │ 2022-01-21   │ George MacKay, Jannis Niewöhner, Jeremy Irons, Robert Bathurst, Jessica Brown Findlay, August Diehl, Sandra Hüller, Alex Jennings, Ulrich Matthes, Liv Lisa Fries                                                                        │ Christian Schwochow │ NULL                                  │ German - Audio Description, German, English - Audio Description, English [Original], Hindi │ German, German, English │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ c94d5145-fc57-584c-bb6a-0535d4ee9cfe │ 2022-03-05 14:51:39 │
│ https://www.netflix.com/title/81194110 │ Tall Girl 2                                      │ Movie       │ Landing the lead in the school musical is a dream come true for Jodi, until the pressure sends her confidence — and her relationship — into a tailspin.  │ 7+            │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABVl_RFKoWoU97Svow-lCbgOISE_N55DPGVKABn9n53BBrBh6lX6RS5BkRqRKzLYI2Q6-4UfSF5t8DKrRRvroO4ilQsgp.jpg?r=2ca │ 1h 41m            │ 2022-02-11   │ Ava Michelle, Griffin Gluck, Sabrina Carpenter, Anjelika Washington, Luke Eisner, Clara Wilsey, Rico Paris, Jan Luis Castellanos, Johanna Liauw, Steve Zahn, Angela Kinsey                                                               │ Emily Ting          │ NULL                                  │ English - Audio Description, English [Original], Hindi, Tamil, Telugu                      │ English                 │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ 62338b6f-a642-5f8e-a846-dc8fb691ddcd │ 2022-03-05 14:51:39 │
│ https://www.netflix.com/title/81028870 │ The Devil All The Time                           │ Movie       │ Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality.  │ 18+           │ US Movies                    │ https://occ-0-1492-1007.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABfZgkFCUnggcSEVxlWY3tLvb-yKK9Jaip_EfdY9yJt9mgWskHqHqXVsexqcwCTPs_PLuyiazDHRYiE8dTBEyCo3-hclG.jpg?r=dd1 │ 2h 18m            │ 2020-09-16   │ Tom Holland, Bill Skarsgård, Riley Keough, Robert Pattinson, Mia Wasikowska, Jason Clarke, Sebastian Stan, Haley Bennett, Harry Melling, Eliza Scanlen                                                                                   │ Antonio Campos      │ NULL                                  │ English - Audio Description, English [Original]                                            │ English                 │ Available to download │            NULL │ NULL            │ Netflix │ https://netflix.com │ 6ff23afd-bc51-5a3d-99cf-464ff3bed09b │ 2022-03-05 14:51:39 │
├────────────────────────────────────────┴──────────────────────────────────────────────────┴─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────┴──────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────┴──────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴───────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────┴───────────────────────┴─────────────────┴─────────────────┴─────────┴─────────────────────┴──────────────────────────────────────┴─────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     21 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
>

In [7]:
#LEER ARCHIVOS PARQUET
conn.sql("""
 SELECT * FROM read_parquet('data/*.parquet')
""")

┌──────────┬────────────┬──────────────────┬────────────────────────────┬───────┬───────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────┬──────────────────┬──────────────────┬───────────────────────┬────────────────────────────┬────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────┬─────────────┬──────────────┬───────────────┬────────────────┬──────────┬──────────────────────────┬──────────────────────────┐
│    Id    │ PostTypeId │ AcceptedAnswerId │        CreationDate        │ Score │ ViewCount │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Body                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │ OwnerUserId │ OwnerDisplayName │ LastEditorUserId │ LastEditorDisplayName │        LastEditDate        │      LastActivityDate      │                                                    Title                                                    │                               Tags                                │ AnswerCount │ CommentCount │ FavoriteCount │ ContentLicense │ ParentId │    CommunityOwnedDate    │        ClosedDate        │

In [ ]:
#SEGUNDO MEDOTO DE CONEXION
#En ese caso si van a usar este segundo metodo deben reinicar el kernel. Otra opción es separar esta parte en otro notebook para que no haya errores entre las DB que se están ejecutando.

In [6]:
#https://duckdb.org/docs/guides/python/jupyter
#Documentación oficial

In [9]:
!pip install  jupysql

Collecting jupysql
  Using cached jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Collecting prettytable>=3.12.0 (from jupysql)
  Using cached prettytable-3.16.0-py3-none-any.whl.metadata (33 kB)
Collecting sqlalchemy (from jupysql)
  Using cached sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting sqlparse (from jupysql)
  Using cached sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Collecting ipython-genutils>=0.1.0 (from jupysql)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: jinja2 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from jupysql) (27.8.0)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Using cached jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Using cached ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: pyyaml in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.2)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-6.7.4-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: wcwidth in c:\users\asustuf\appdata\roaming\python\python313\site-packages (from prettytable>=3.12.0->jupysql) (0.2.13)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from jinja2->jupysql) (3.0.2)
Collecting greenlet>=1 (from sqlalchemy->jupysql)
  Using cached greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy->jupysql) (4.13.2)
Requirement already satisfied: requests<3.0,>=2.7 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.3)
Requirement already satisfied: six>=1.5 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.9.0.post0)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting distro>=1.5.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2025.1.31)
Using cached jupysql-0.11.1-py3-none-any.whl (95 kB)
Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Using cached jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
Using cached ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Using cached prettytable-3.16.0-py3-none-any.whl (33 kB)
Using cached sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl (2.1 MB)
Using cached sqlparse-0.5.3-py3-none-any.whl (44 kB)
Using cached greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Downloading posthog-6.7.4-py3-none-any.whl (136 kB)
Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Installing collected packages: ipython-genutils, sqlparse, prettytable, greenlet, distro, backoff, sqlalchemy, posthog, ploomber-core, jupysql-plugin, jupysql
Successfully installed backoff-2.2.1 distro-1.9.0 greenlet-3.2.4 ipython-genutils-0.2.0 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-6.7.4 prettytable-3.16.0 sqlalchemy-2.0.43 sqlparse-0.5.3

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
!pip install duckdb-engine

Collecting duckdb-engine
  Using cached duckdb_engine-0.17.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: duckdb>=0.5.0 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from duckdb-engine) (1.2.2)
Requirement already satisfied: packaging>=21 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from duckdb-engine) (24.2)
Requirement already satisfied: sqlalchemy>=1.3.22 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from duckdb-engine) (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asustuf\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy>=1.3.22->duckdb-engine) (4.13.2)
Using cached duckdb_engine-0.17.0-py3-none-any.whl (49 kB)
Installing collected packages: duckdb-engine
Successfully installed duckdb-engine-0.17.0

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import duckdb
import pandas as pd
# No need to import duckdb_engine
#  jupysql will auto-detect the driver needed based on the connection string!
# Import jupysql Jupyter extension to create SQL cells
%load_ext sql

In [2]:
# Configuraciones para formato de datos
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

In [11]:
#Aqui podemos definir si queremos que la base de datos sea en memoria o se guarde en un archivo en especifico. Si solo están haciendo pruebas, usar la opción memory

In [ ]:
%sql duckdb:///:memory:
#Usar una base de datos en memoria

In [40]:
#%sql duckdb:///:default:
# Usar la conexión predeterminada de DuckDB

In [ ]:
#%sql duckdb:///path/to/file.db
#Usar un archivo como base de datos persistente
#%sql duckdb:///C:/Users/AsusTUF/Desktop/UAO/Semana_2/duckdb/venv/nyc-parking-tickets.db

In [12]:
#LEER CSV
%sql SELECT * FROM read_csv('data/*.csv')

,url,name,contentType,description,contentRating,genre,poster,formattedDuration,releasedDate,actors,...,creator,audio,subtitle,availableForOffline,numberOfSeasons,seasonStartDate,source,sourceLink,uniqId,scrapedAt
0,https://www.netflix.com/title/80189221,The Haunting of Hill House,TVSeries,"Flashing between past and present, a fractured...",18+,TV Mysteries,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2018-10-12,"Michiel Huisman, Carla Gugino, Timothy Hutton,...",...,Mike Flanagan,None,None,Available to download,1,2018-10-12,Netflix,https://netflix.com,85814dcd-729d-577f-873b-e3b7d9f21ab1,2022-03-05 14:51:34
1,https://www.netflix.com/title/81031373,Don't F**k with Cats: Hunting an Internet Killer,TVSeries,A twisted criminal's gruesome videos drive a g...,18+,True Crime Documentaries,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2019-12-18,None,...,None,None,None,Available to download,1,2019-12-18,Netflix,https://netflix.com,134f93fc-a991-55ca-ad36-8c438b930e52,2022-03-05 14:51:36
2,https://www.netflix.com/title/80996601,Love Is Blind,TVSeries,Nick and Vanessa Lachey host this social exper...,16+,Wedding & Romance Reality TV,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2020-02-13,"Nick Lachey, Vanessa Lachey",...,None,None,None,Available to download,2,2020-02-13,Netflix,https://netflix.com,e5461057-25c2-59a5-8672-d4b4a102ee00,2022-03-05 14:51:37
3,https://www.netflix.com/title/81350429,I Care a Lot,Movie,A court-appointed legal guardian defrauds her ...,18+,US Movies,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,1h 59m,2021-02-19,"Rosamund Pike, Peter Dinklage, Eiza González, ...",...,None,"English - Audio Description, English [Original]","English, Hindi",Available to download,<NA>,NaT,Netflix,https://netflix.com,bbc71932-fc79-51aa-bf83-023c2c5db97c,2022-03-05 14:51:37
4,https://www.netflix.com/title/81149184,"tick, tick...BOOM!",Movie,"On the brink of turning 30, a promising theate...",13+,US Movies,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,1h 55m,2021-11-19,"Andrew Garfield, Alexandra Shipp, Vanessa Hudg...",...,None,"English - Audio Description, English [Original...",English,Available to download,<NA>,NaT,Netflix,https://netflix.com,cd630201-99b9-5ac4-bb78-7fad5c65cc95,2022-03-05 14:51:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,https://www.netflix.com/title/81021929,Space Force,TVSeries,A four-star general begrudgingly teams up with...,16+,TV Comedies,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2020-05-29,"Steve Carell, John Malkovich, Ben Schwartz, Di...",...,"Steve Carell, Greg Daniels",None,None,Available to download,2,2020-05-29,Netflix,https://netflix.com,72e2a0af-02a1-5d25-9a1d-eb74cd82e6b8,2022-03-05 14:56:58
144,https://www.netflix.com/title/81123055,In From the Cold,TVSeries,"Exposed as an ex-Russian spy, an American sing...",18+,TV Thrillers,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2022-01-28,"Margarita Levieva, Cillian O'Sullivan, Lydia F...",...,Adam Glass,None,None,Available to download,1,2022-01-28,Netflix,https://netflix.com,030c5bef-bf17-5e3c-874a-5248a0fc798c,2022-03-05 14:56:58
145,https://www.netflix.com/title/81036622,Toy Boy,TVSeries,"After seven years in a Málaga prison, a male s...",18+,TV Thrillers,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2020-02-28,"Jesús Mosquera, Cristina Castaño, María Pedraz...",...,"César Benítez, Juan Carlos Cueto, Rocío Martín...",None,None,Available to download,2,2020-02-28,Netflix,https://netflix.com,957197b0-7cec-58aa-9c78-62fc50e1fe74,2022-03-05 14:56:58
146,https://www.netflix.com/title/81464765,14 Peaks: Nothing Is Impossible,Movie,Fearless Nepali mountaineer Nimsdai Purja emba...,13+,Documentaries,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,1h 41m,2021-11-29,None,...,None,"English - Audio Description, English [Original...",English,Available to download,<NA>,NaT,Netflix,https://netflix.com,cd828c29-8ecd-54b1-8c12-e8911dac5c2e,2022-03-05 14:56:59
147,https://www.netflix.com/title/81435684,Arcane,TVSeries,Amid the stark discord of twin cities Piltover...,16+,Fantasy TV Shows,https://occ-0-1492-1007.1.nflxso.net/dnm/api/v...,None,2021-11-07,"Hailee Steinfeld, Katie Leung, Kevin Alejandro...",...,"Christian Linke, Alex Yee",None,None,Available to download,1,2021-11-07,Netflix,https://netflix.com,2b0b2a1f-a3e4-55f5-96cb-8015d4ae8817,2022-03-05 14:56:59

In [13]:
#LEER PARQUET
%sql SELECT * FROM read_parquet('data/*.parquet')

,Id,PostTypeId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,LastEditorUserId,...,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ContentLicense,ParentId,CommunityOwnedDate,ClosedDate
0,62804633,1,62804782,2020-07-08 17:31:07.570000-05:00,0,338,"[60, 112, 62, 73, 39, 109, 32, 116, 114, 121, ...",12487679,[],13536893,...,2020-07-09 03:21:35.250000-05:00,"[74, 97, 118, 97, 115, 99, 114, 105, 112, 116,...","[124, 106, 97, 118, 97, 115, 99, 114, 105, 112...",2,1,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]",[],1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
1,62804673,1,0,2020-07-08 17:35:23.037000-05:00,0,106,"[60, 112, 62, 73, 32, 104, 97, 118, 101, 32, 1...",11747882,[],1127428,...,2020-07-09 17:17:30.023000-05:00,"[84, 97, 98, 108, 101, 32, 118, 97, 108, 117, ...","[124, 115, 113, 108, 45, 115, 101, 114, 118, 1...",1,1,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]",[],1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
2,62804682,1,0,2020-07-08 17:36:21.983000-05:00,-1,42,"[60, 112, 62, 97, 32, 61, 32, 91, 49, 44, 50, ...",12065990,[],0,...,2020-07-08 20:29:11.930000-05:00,"[72, 111, 119, 32, 116, 111, 32, 100, 101, 108...","[124, 112, 121, 116, 104, 111, 110, 45, 51, 46...",1,1,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]",[],1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
3,62804703,1,0,2020-07-08 17:38:51.307000-05:00,0,4002,"[60, 112, 62, 73, 32, 97, 109, 32, 116, 114, 1...",13826610,[],13826610,...,2020-07-11 08:03:52.197000-05:00,"[108, 111, 99, 97, 116, 105, 111, 110, 32, 105...","[124, 102, 108, 117, 116, 116, 101, 114, 124]",1,1,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]",[],1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
4,62804732,1,62840655,2020-07-08 17:42:26.510000-05:00,2,372,"[60, 112, 62, 73, 32, 104, 97, 118, 101, 32, 9...",12504598,[],12504598,...,2020-07-10 13:52:45.493000-05:00,"[67, 111, 110, 116, 114, 111, 108, 108, 105, 1...","[124, 106, 97, 118, 97, 115, 99, 114, 105, 112...",1,1,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]",[],1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4304016,62293139,2,0,2020-06-09 17:50:09.013000-05:00,1,0,"[60, 112, 62, 84, 104, 101, 32, 112, 117, 114,...",13095326,[],13095326,...,2020-06-09 18:02:22.910000-05:00,[],[],0,0,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]","[54, 50, 50, 57, 51, 48, 52, 52]",1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
4304017,62293150,2,0,2020-06-09 17:50:59.660000-05:00,2,0,"[60, 112, 62, 87, 105, 116, 104, 32, 100, 101,...",11839686,[],0,...,2020-06-09 17:50:59.660000-05:00,[],[],0,0,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]","[54, 50, 50, 57, 48, 53, 57, 52]",1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
4304018,62293155,2,0,2020-06-09 17:51:38.120000-05:00,0,0,"[60, 112, 62, 73, 32, 104, 97, 118, 101, 32, 9...",1051256,[],0,...,2020-06-09 17:51:38.120000-05:00,[],[],0,0,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]","[52, 56, 50, 49, 57, 52, 51, 50]",1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
4304019,62293162,2,0,2020-06-09 17:52:42.670000-05:00,0,0,"[60, 112, 62, 70, 105, 120, 101, 100, 32, 109,...",11417831,[],0,...,2020-06-09 17:52:42.670000-05:00,[],[],0,0,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]","[54, 50, 50, 53, 50, 53, 56, 57]",1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00
4304020,62293166,2,0,2020-06-09 17:53:05.897000-05:00,0,0,"[60, 112, 114, 101, 62, 60, 99, 111, 100, 101,...",13662509,[],0,...,2020-06-09 17:53:05.897000-05:00,[],[],0,0,0,"[67, 67, 32, 66, 89, 45, 83, 65, 32, 52, 46, 48]","[54, 50, 49, 52, 52, 50, 55, 54]",1969-12-31 19:00:00-05:00,1969-12-31 19:00:00-05:00

In [14]:
%sql SELECT count(*) FROM read_parquet('data/*.parquet')

   count_star()
0       4304021

In [15]:
#SABER SI ESTAMOS TRAYENDO LOS DATOS EN LA RUTA ESPECIFICA
import os
print(os.listdir("data/"))

['2020.parquet', 'netflix_movies_and_tv_shows_sample_dataset_sample.csv', 'parquet']

In [27]:
import duckdb
import pandas as pd

con = duckdb.connect()

df = con.execute("SELECT count(*) AS total FROM read_parquet('data/parquet/*.parquet')").fetchdf()
print(df)

     total
0  3475226

In [28]:
df.head()

     total
0  3475226

In [29]:
df = con.execute("SELECT * FROM read_parquet('data/parquet/*.parquet')").fetchdf()

In [30]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1,1.60,1,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1,0.50,1,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1,0.60,1,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3,0.52,1,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3,0.66,1,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [31]:
num_dupes = df.duplicated().sum()
print(num_dupes)

0